/* Generated By:JavaCC: Do not edit this line. ArcParserConstants.java */
package rainbow.parser;

public interface ArcParserConstants {

  int EOF = 0;
  int FRACTION = 5;
  int DOUBLE = 6;
  int UNSIGNED_DOUBLE = 7;
  int DOUBLE1 = 8;
  int DOUBLE2 = 9;
  int INTEGER = 10;
  int UNSIGNED_INTEGER = 11;
  int DIGIT = 12;
  int SIGN = 13;
  int IDENTIFIER = 14;
  int INITIAL = 15;
  int LETTER = 16;
  int SPECIAL_INITIAL = 17;
  int SPECIAL_SUBSEQUENT = 18;
  int SUBSEQUENT = 19;
  int STRING = 20;
  int STRING_ELEMENT = 21;
  int DOT = 22;
  int CHARACTER = 23;
  int SINGLE_CHARACTER = 24;
  int NEWLINE_CHARACTER = 25;
  int TAB_CHARACTER = 26;
  int SPACE_CHARACTER = 27;
  int RETURN_CHARACTER = 28;
  int NULL_CHARACTER = 29;
  int ASCII_CHARACTER = 30;
  int UNICODE_CHARACTER = 31;
  int COMMENT = 32;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "<FRACTION>",
    "<DOUBLE>",
    "<UNSIGNED_DOUBLE>",
    "<DOUBLE1>",
    "<DOUBLE2>",
    "<INTEGER>",
    "<UNSIGNED_INTEGER>",
    "<DIGIT>",
    "<SIGN>",
    "<IDENTIFIER>",
    "<INITIAL>",
    "<LETTER>",
    "<SPECIAL_INITIAL>",
    "<SPECIAL_SUBSEQUENT>",
    "<SUBSEQUENT>",
    "<STRING>",
    "<STRING_ELEMENT>",
    "\".\"",
    "<CHARACTER>",
    "<SINGLE_CHARACTER>",
    "\"#\\\\newline\"",
    "\"#\\\\tab\"",
    "\"#\\\\space\"",
    "\"#\\\\return\"",
    "\"#\\\\null\"",
    "<ASCII_CHARACTER>",
    "<UNICODE_CHARACTER>",
    "<COMMENT>",
    "\"\\\'\"",
    "\",\"",
    "\",@\"",
    "\"`\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
  };

}
